name: Build Fast Transformers Utils

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Fast Transformers Utils Version to Build'
        required: true
        default: '1.0.0'
      platform:
        description: 'Platform to Build On'
        required: true
        default: 'all'
        type: choice
        options:
          - linux
          - windows
          - macos
          - all

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: linux
            os: ubuntu-latest
            configure-options: ''
          - platform: windows
            os: windows-latest
            configure-options: -DCMAKE_TOOLCHAIN_FILE=c:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=True
          - platform: macos
            os: macos-latest
            configure-options: ''
      fail-fast: false
      max-parallel: 3

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: CodeWithKyrian/fast_transformers_utils
          ref: ${{ github.event.inputs.version }}

      - name: Create CMake Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Build Fast Transformers Utils
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake ${{github.workspace}} -DCMAKE_BUILD_TYPE=Release ${{matrix.configure-options}}
          cmake --build . --config Release
          cpack -C Release -G TGZ

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fast_transformers_utils-${{ github.event.inputs.version }}-${{ matrix.platform }}
          path: ${{ runner.workspace }}/build/*.tar.gz

  build-linux-arm64:
    if: github.event.inputs.platform == 'linux' || github.event.inputs.platform == 'all'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: CodeWithKyrian/fast_transformers_utils
          ref: ${{ github.event.inputs.version }}

      - name: Build Fast Transformers Utils
        uses: pguyot/arm-runner-action@v2
        with:
          base_image: raspios_lite_arm64:2023-05-03
          cpu: cortex-a53
          cpu_info: cpuinfo/raspberrypi_zero2_w_arm64
          bind_mount_repository: true
          commands: |
            sudo apt-get update -y
            sudo apt-get install -y cmake
            
            mkdir build
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release
            cmake --build . --config Release
            cpack -C Release -G TGZ

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fast_transformers_utils-${{ github.event.inputs.version }}-linux-arm64
          path: build/*.tar.gz
