name: Build Samplerate

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Samplerate Version to Build'
        required: true
        default: '0.2.2'
      platform:
        description: 'Platform to Build On'
        required: true
        default: 'all'
        type: choice
        options:
          - linux
          - windows
          - macos
          - all

jobs:
    build:
        strategy:
          matrix:
              include:
              - platform: linux
                os: ubuntu-latest
                configure-options: ''
              - platform: windows
                os: windows-latest
                configure-options: -DCMAKE_TOOLCHAIN_FILE=c:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows
              - platform: macos
                os: macos-latest
                configure-options: ''
          fail-fast: false
          max-parallel: 3

        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                repository: libsndfile/libsamplerate
                ref: ${{ github.event.inputs.version }}

            - name: Install Dependencies (Linux)
              if: matrix.platform == 'linux'
              run: |
                sudo apt-get update -y
                sudo apt-get install -y libsndfile-dev libopus-dev libfftw3-dev libasound2-dev

            - name: Install Dependencies (MacOS)
              if: matrix.platform == 'macos'
              run: |
                brew install automake libtool libsndfile fftw

            - name: Install Dependencies (Windows)
              if: matrix.platform == 'windows'
              run: |
                vcpkg install libsndfile:x64-windows opus:x64-windows fftw3:x64-windows

            - name: Create CMake Build Environment
              run: cmake -E make_directory ${{runner.workspace}}/build

            - name: Build Samplerate
              working-directory: ${{runner.workspace}}/build
              run: |
                cmake ${{github.workspace}} -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON ${{matrix.configure-options}}
                cmake --build . --config Release
                cpack -C Release -G TGZ

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: libsamplerate-${{ github.event.inputs.version }}-${{ matrix.platform }}
                  path: ${{ runner.workspace }}/build/*.tar.gz

    build-linux-arm64:
        name: Build Linux ARM64
        if: github.event.inputs.platform == 'linux' || github.event.inputs.platform == 'all'
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4
            with:
              repository: OpenMathLib/OpenBLAS
              ref: ${{ github.event.inputs.version }}

          - name: Build Samplerate
            uses: pguyot/arm-runner-action@v2
            with:
              base_image: raspios_lite_arm64:2022-04-04
              cpu: cortex-a53
              cpu_info: cpuinfo/raspberrypi_zero2_w_arm64
              bind_mount_repository: true
              commands: |
                sudo apt-get install -y libsndfile-dev libopus-dev libfftw3-dev libasound2-dev
                
                cmake -E make_directory ${{runner.workspace}}/build
                cmake ${{github.workspace}} -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
                cmake --build . --config Release
                cpack -C Release -G TGZ

          - name: Upload Artifact
            uses: actions/upload-artifact@v4
            with:
              name: libsamplerate-${{ github.event.inputs.version }}-linux-arm64
              path: ${{ runner.workspace }}/build/*.tar.gz